### ISSUE TITLE
Highcharts series types are listed in Highmaps

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#12]
Only six series types exist in Highmaps, see http://api.highcharts.com/highmaps/plotOptions

Are product tags missing on the optionparents?

```js
seriesType('area', 'line', 
	/**
	 * @extends {plotOptions.line}
	 * @optionparent plotOptions.area
	 */
	{
```

**Comment by cvasseng** [comment]
They need to be manually added along with `@optionparent` pre-patch.

**Comment by TorsteinHonsi** [comment]
The same applies to Highstock.

**Comment by cvasseng** [comment]
Yeah, I'm not patching `@product` in on the top levels, since it will be more reliable if it's done manually. So it needs to be done manually when the `@optionparent` tags are verified (there may still be some that are missing).
