### ISSUE TITLE
Differences in properties between products are not respected

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#17]
Example 1, the top level description for xAxis should be different between Highcharts an Highmaps: http://api.highcharts.com/highcharts/xAxis, http://api.highcharts.com/highmaps/xAxis.

Example 2, http://api.highcharts.com/highmaps/xAxis.allowDecimals has a different description in Highmaps. 

Example 3, http://api.highcharts.com/highstock/title.text. Highstock has title.text to null by default, while it is `Chart title` in Highcharts.

While preparing a fix for this, we should print out a list of the corresponding properties that have different values (including different default value).

____
Edit: The safest approach, at least initially, would be to maintain completely separate doclets for the products in cases where any property differs. Later we can explore the possibility of allowing differences in specific properties, like @defaults, or @sample's that are filtered by product.

**Comment by TorsteinHonsi** [comment]
Check no 4: Highcharts has default font size 18px, Highstock has 16px: 

http://api.highcharts.com/highcharts/title.style
http://api.highcharts.com/highstock/title.style

Check no 5: Under title.style, check that the samples are different.

**Comment by TorsteinHonsi** [comment]
Conclusion:

1. We will try using JSDoc's type system to filter _@sample_ and _@defaults_  tags by product:
`@sample [highstock] stock/legend/enabled Legend enabled`.

```js
@defaults 20
@defaults [highmaps] 8
```
Christer will update the patch script to handle these two properties.

2. We will use the type system to allow product specific descriptions: `@description [highstock] Bla bla bla.` These will be added below the generic description. Once this is implemented, Torstein reviews the content manually.

**Comment by cvasseng** [comment]
`@sample {product} ....` and `@default {product} ....` has been added to the patch generator in `jsdoc-patch` (497e30c). The latter will also check if all defaults are the same across products, in which case it will collapse to a single `@default`-tag with the "type" set to `{all}`.

**Comment by TorsteinHonsi** [comment]
To do:
- Christer adds proper parsing of products for the API generator
- Torstein manually reviews all descriptions with differing content.

**Comment by TorsteinHonsi** [comment]
Conclusion: Torstein implemented `@productdesc` tag.
