### ISSUE TITLE
Default values should be filtered by product

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#19]
Products are given in curly brackets:

`@default {highcharts} true`

Multiple products should be supported:

`@default {highcharts|highstock} true`

When left out, the default should apply to all products:

`@default true`

Multiple tags should be supported on each doclet:

```js
@default {highcharts|highstock} true
@default {highmaps} false
```

**Comment by cvasseng** [comment]
Fixed in plugin (https://github.com/highcharts/highcharts/commit/b8c706cc746078275ce3a855167946b3c473d8c4) + in 1e4fb6220e4859b9482f4cfe634bc76627630d74
