### ISSUE TITLE
Move lang and global structures to Highcharts.setOptions

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#2]
It should be like this:

![skjermbilde 2017-06-16 kl 12 42 25](https://user-images.githubusercontent.com/227836/27223576-4cac0ee0-5291-11e7-88c0-85670ced1c33.png)

**Comment by cvasseng** [comment]
What does it look like for you?

Here's how it looks like here:

![screen shot 2017-06-16 at 13 07 15](https://user-images.githubusercontent.com/1998167/27224321-cf2f91d6-5294-11e7-8455-39b4b3c403e5.png)

**Comment by TorsteinHonsi** [comment]
Version confusion, closing.
