### ISSUE TITLE
Inheritance problems

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#23]
http://localhost:8000/highcharts/plotOptions.column.states.hover.html

The column hover state is missing `borderColor` and `color` as defined in ColumnSeries.js.

On the other side, `halo` and `lineWidthPlus` should be excluded.

**Comment by TorsteinHonsi** [comment]
Another case: http://localhost:8000/highcharts/plotOptions.bubble.marker.radius.html
* `fillOpacity` is missing.
* `enabled,height,radius,width` should be excluded.
* The overridden doclet for `symbol` is missing. However, the overridden doclet for `radius` is present.

**Comment by TorsteinHonsi** [comment]
Reopening, this still fails:

> On the other side, `halo` and `lineWidthPlus` should be excluded.

**Comment by cvasseng** [comment]
Sorry, missed that.

This was caused by the plugin expecting `@excluding` while the doclets use `@exclude`. Made an alias + fixed recursive exclude in merge function, so looks to be working now (requires the updated jsdoc plugin).

**Comment by TorsteinHonsi** [comment]
Some more inconsistencies detected in the `solbrest` branch (recently updated from master):

See http://localhost:9005/highcharts/plotOptions.streamgraph.html, code defined in `/modules/streamgraph.src.js`.

* Fails: The `fillOpacity` default value should be 1. 
* Works: The `lineWidth` default is 0.
* Fails: The `marker.enabled` default should be `false`.
* Works: The `stacking` default is `stream`

**Comment by cvasseng** [comment]
Seems to be caused by the lack of a doclet on the streamgraph stuff.

The doclet values have precedence basically, so the inherited stuff overrides it since there's no default set in the doclet.

Working on a fix.

**Comment by cvasseng** [comment]
I've rewritten the merging function. Things look more correct now, but there may be følgefeil I haven't seen yet. So leaving this open.
