### ISSUE TITLE
Default values not always parsed

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#24]
Strings are correctly parsed, while boolean `false`  as well as numbers seems to not be parsed.

Case: `drilldown.drillUpButton.position`, where the default value for `align` is correctly parsed, but not `x` and `y`.

**Comment by TorsteinHonsi** [comment]
Updated: only parsing -10 fails now.

**Comment by cvasseng** [comment]
Fixed in highcharts master: https://github.com/highcharts/highcharts/commit/579ff700707886f6d628b7cb1e4885e8911cd393
