### ISSUE TITLE
Default values of null don't take precedence in inheritance

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#27]
Case: http://localhost:8000/highcharts/plotOptions.errorbar.whiskerWidth.html

The errorbar inherits boxplot. Error bar has a default whiskerWidth of `null`, which has a meaning in Highcharts. This is a common pattern.

**Comment by cvasseng** [comment]
Have you changed anything on the `plotOptions.errorbar.whiskerWidth` doclet?

This looks correct here (see screeny), unless I misunderstand the issue. I see the issue on the other one, so will just look at that to fix it, but want to confirm that we're seeing the same things.

![screen shot 2017-08-04 at 09 22 48](https://user-images.githubusercontent.com/1998167/28958530-f5cb1bca-78f6-11e7-996d-099071af173e.png)

**Comment by TorsteinHonsi** [comment]
This now works correctly for defaults defined in the doclet, but not for righthand side values in expressions:

https://github.com/highcharts/highcharts/blob/579ff7007/js/parts-more/ErrorBarSeries.js#L43-#L43
http://localhost:9005/highcharts/plotOptions.errorbar.grouping.html

**Comment by cvasseng** [comment]
Both of those cases seem to be working now.
