### ISSUE TITLE
Samples of extended parent override current item

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#28]
Case: http://localhost:8000/highcharts/plotOptions.errorbar.whiskerWidth.html

The samples listed here are inherited from the parent, while the one sample actually defined for the error bar is not listed.

I think the best practice would be to not list samples from the parent, and completely remove then and replace them by samples from the current item.

**Comment by TorsteinHonsi** [comment]
Brutally removing samples from parent causes all samples to be gone from inherited series types, which are alle except `plotOptions.series`. We need to do this smarter. Perhaps just remove parent samples if there is actually defined a sample in the child.

**Comment by bre1470** [comment]
Is this still an issue?
