### ISSUE TITLE
Error in generating API

### ISSUE THREAD

**Issue by pawelfus** [highcharts/api-docs#31]
It looks like I have some problems with jsdoc-api generator. Details:

> $ gulp jsdoc --watch
> [11:58:08] Using gulpfile ~/projects/projects/highcharts/gulpfile.js
> [11:58:08] Starting ‘jsdoc’...
> Watching file changes in JS files and templates
> Starting API docs server http://localhost:9005
> [11:58:11] Documented 24 files!
> [11:58:11] Finished ‘jsdoc’ after 3.16 s
> Created class-reference
> [11:58:12] /Users/pawelfus/projects/projects/highcharts/tools/jsdoc/plugins/highcharts.jsdoc.js:168
>        s = comment.indexOf(‘@optionparent’);
>
> TypeError: Cannot read property ‘indexOf’ of undefined
>    at Object.nodeVisitor [as visitNode] (/Users/pawelfus/projects/projects/highcharts/tools/jsdoc/plugins/highcharts.jsdoc.js:168:20)
> …

In the highcharts.jsdoc.js file, this is responsible line:

    comment = node.leadingComments[0].raw;

Changing to 
 
    comment = node.leadingComments[0].raw || ‘’;

generates api docs, however I’m not sure what exactly happens here. @christer ?

**Comment by cvasseng** [comment]
We saw the same issue in the plugin for the cloud.

Basically jsdoc changed their AST API between `3.4.x` to `3.5.x`, which is why it breaks..

**Comment by pawelfus** [comment]
Changing version to 3.4.x doesn't change anything. Still the same issue. It is really strange, following docs:

- [jdoc](http://usejsdoc.org/about-plugins.html#node-visitors): 
  > node: The AST node. AST nodes are JavaScript objects that use the format defined by the ESTree spec. You can use AST Explorer to see the AST that will be created for your source code. As of version 3.5.0, JSDoc uses the current version of the Babylon parser with all plugins enabled.

- [AST node example](https://astexplorer.net/): dosn't show property `raw`, however:

- [Esprima](http://esprima.readthedocs.io/en/4.0/syntax-tree-format.html?highlight=raw#literal) in the docs shows `raw` position. Of course, 3.5.0 with Babylon doesn't have this value.

Anyway, for now I use:
`comment = node.leadingComments[0].raw || node.leadingComments[0].value.toString();`

**Comment by pawelfus** [comment]
Ok, it works with:

- jsdoc@**3.4.3**
- and manually added `taffydb` module

**Comment by TorsteinHonsi** [comment]
Node v8.5 broke jsDoc v3.4 which in turn forced me to upgrade to jsdoc v 3.5.5 which eventually brought me here. 

I fixed the `raw` problem above by using `value` instead, which seems to work in that particular place.

Two problems now as far as I can see:
* _credits_ and _tooltip_ are missing children.
* Top level descriptions are missing some places, for example in legend. 

@cvasseng Do we have a plan for migrating/debugging? For now I can just leave the build process to someone with an older version of node, but eventually time will catch up with us all.

**Comment by cvasseng** [comment]
There's no concrete plans, but we need better routines I think.

The new node broke the cloud deployments too as a side note. Annoying.

**Comment by TorsteinHonsi** [comment]
Fixed now.
