### ISSUE TITLE
New lines inside code blocks are messing things up

### ISSUE THREAD

**Issue by cvasseng** [highcharts/api-docs#37]
In cases where a doclet is defined as such:

```
/**
* A custom class name, in addition to the default `highcharts-plot-
* line`, to apply to each individual line.
*/
```

there's an extra space in the output (`highcharts-plot- line`). There are also several cases of straight up newlines inside doclet descriptions, which leads to e.g. `highcharts-plot-\nband`.

**Comment by TorsteinHonsi** [comment]
After a short discussion, we concluded that:
1. The markdown spec doesn't allow newlines inside backtick blocks. Subsequently, this is an error in the content, not the parser.
2. We should add a linting rule to https://github.com/highcharts/eslint-plugin-highcharts to pick it up.
