### ISSUE TITLE
Is AAChartKit legal which is based on Highcharts?

### ISSUE THREAD

**Issue by YouMotherFucker** [highcharts/api-docs#38]
## [AAChartKit](https://github.com/AAChartModel/AAChartKit)

>  AAChartKit is an elegant, friendly and easy to use chart library for iOS, based on the open source Highcharts JS libraries. AAChartKit is extremely powerful, easy to configure and a pleasure to use. Currently AAChartKit includes support for the following chart types: column chart, bar chart, area chart, area spline chart, line chart, spline chart, radar chart, polar chart, pie chart, bubble chart, pyramid chart, funnel chart, column range and area range chart. More chart types are planned to be supported. AAChartKit gives you easy and fast access to a wide range of chart types, hassle free and quickly to integrate into your own project.

AAChartKit is a great project for iOS developer to use Highcharts without any annoying problem, even better and more easy to use than the Highcharts official project as for me.However I know the Highcharts is not free for commercial user who want to make money with Highcharts. Considering of the AAChartKit is released under MIT license,I not sure it is legal to use AAChartKit in my project and the author of AAChartKit should be responsible for that?
Is AAChartKit really legal even if the author is not for money to release the source code?

**Comment by sophiebremer** [comment]
I am sorry, for the late response. Please use next time our support channels.

AAChartKit has changed the LICENSE of the Highcharts sources and is by itself not a legal fork, but the use of AAChartKit is still covered, when you get a Highcharts license.
