### ISSUE TITLE
Feature request: add support for product blacklisting

### ISSUE THREAD

**Issue by cvasseng** [highcharts/api-docs#49]
Adding support for product blacklisting in the `@products` tag would make things less verbose in situations where e.g. an option is enabled for 3/4 products.

The syntax could be:
```
@products  -highmaps
```

In order to retain compatibility with other tools, this should be rewritten automatically during the parsing stage to the current whitelisting form.

**Comment by bre1470** [comment]
This requires a list of all possible products somewhere.

**Comment by bre1470** [comment]
Maybe we should centralize this, for example introduce a jsdoc.json in the root folder. Right now we have in the api-docs, gulpfile, jsdoc plugin, and declarations generator product lists.

**Comment by bre1470** [comment]
Is referenced in the repository: 
https://github.com/highcharts/highcharts-documentation-generators/issues/1
