### ISSUE TITLE
Markdown in @see is not completely/correctly parsed.

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#5]
http://localhost:9700/highcharts/chart.backgroundColor.html

![skjermbilde 2017-06-16 kl 13 26 53](https://user-images.githubusercontent.com/227836/27224836-8e759e44-5297-11e7-963b-555f6f0b1a6f.png)

**Comment by cvasseng** [comment]
The markdown in the tree actually looks right, but the frontend isn't displaying it correctly.
