### ISSUE TITLE
yAxis.endOnTick true example send to reflow example

### ISSUE THREAD

**Issue by jbkunst** [highcharts/api-docs#62]
Hi, not sure if this issues is correct in this repo.

In https://api.highcharts.com/highcharts/yAxis.endOnTick yAxis.endOnTick true example send to reflow example https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/reflow-true/

![image](https://user-images.githubusercontent.com/56481/121714688-175ba600-caac-11eb-9274-0b24223d87f1.png)

**Comment by bre1470** [comment]
Hello @jbkunst! Thank you for the feedback. I will move the ticket to our main repository, because the documentation is maintained by source comments.
