### ISSUE TITLE
Newlines are not preserved inside <pre> tags

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#7]
![skjermbilde 2017-06-16 kl 13 36 34](https://user-images.githubusercontent.com/227836/27225100-f952a0a8-5298-11e7-8c57-32809d1f85b1.png)

**Comment by cvasseng** [comment]
Note to self: They're eaten by the markdown converter in `generate_patch_script:102`.

Possible solution is to not mess with newlines and hope that the markdown converter leaves them alone, but that requires modifying the 80-character aligner.

**Comment by cvasseng** [comment]
Fixed in push to `jsdoc-patch` in the Highcharts repository.
