### ISSUE TITLE
Context missing from callbacks (add to UI/frontend)

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/api-docs#8]
The existing API has context information, I think from a simple `context` property in the document.

![skjermbilde 2017-06-16 kl 13 40 43](https://user-images.githubusercontent.com/227836/27225217-7ab5463c-5299-11e7-825d-c5f317199447.png)

**Comment by cvasseng** [comment]
Turns out this was there all along, it's just not shown in the front end.
